rules = {
    "due": "Due by + heure Due on + jour de la semaine",
    "used to": "USED TO + BV pour parler d'une habitude passée qui n'est plus d'actualité.",
    "would rather": "WOULD RATHER + BV pour exprimer une préférence.",
    "be used to": "BE USED TO + V-ING pour parler d'une habitude actuelle.",
    "so that": "SO THAT + sujet + modalité (can, could, may, might) pour exprimer une finalité.",
    "since": "Utilisé pour indiquer le début d'une période de temps : SINCE + point dans le passé.",
    "for": "Utilisé pour indiquer la durée : FOR + période de temps.",
    "present perfect": "HAVE/HAS + participe passé pour parler d'une action passée avec un lien au présent.",
    "present continuous": "BE + V-ING pour parler d'actions en cours ou d'événements futurs planifiés.",
    "past simple": "Verbe au passé simple pour parler d'actions terminées dans le passé.",
    "past continuous": "WAS/WERE + V-ING pour parler d'une action qui était en cours à un moment précis dans le passé.",
    "conditional type 1": "IF + présent simple, WILL + BV pour parler d'une condition réelle ou possible dans le futur.",
    "conditional type 2": "IF + prétérit, WOULD + BV pour parler d'une condition hypothétique ou irréaliste dans le présent.",
    "conditional type 3": "IF + past perfect, WOULD HAVE + participe passé pour parler d'une condition passée irréalisable.",
    "comparative adjectives": "Adjectifs courts : adj + -ER THAN. Adjectifs longs : MORE + adj + THAN.",
    "superlative adjectives": "Adjectifs courts : THE + adj + -EST. Adjectifs longs : THE MOST + adj.",
    "enough": "Assez : ENOUGH + nom (assez de...) / adj + ENOUGH (suffisamment...)",
    "too": "Trop : TOO + adj (trop...) / TOO MUCH + nom (trop de...).",
    "passive voice": "BE + participe passé pour mettre l'accent sur l'action plutôt que sur qui la fait.",
    "question tags": "Court ajout à la fin d'une phrase pour demander confirmation. Ex : It's raining, isn't it?",
    "must vs have to": "MUST pour l'obligation personnelle. HAVE TO pour l'obligation extérieure ou imposée.",
    "may/might": "MAY/MIGHT + BV pour exprimer une possibilité ou une probabilité faible.",
    "should": "SHOULD + BV pour donner un conseil ou exprimer une suggestion.",
    "future continuous": "WILL BE + V-ING pour parler d'une action qui sera en cours à un moment futur.",
    "future perfect": "WILL HAVE + participe passé pour parler d'une action qui sera terminée à un moment précis dans le futur.",
    "relative pronouns": "WHO (personne), WHICH (chose), THAT (personne/chose) pour introduire une subordonnée relative.",
    "who vs whom": "WHO pour le sujet, WHOM pour l'objet dans une subordonnée relative.",
    "either...or": "EITHER...OR pour exprimer une alternative positive. Ex : You can either call me or send an email.",
    "neither...nor": "NEITHER...NOR pour exprimer une double négation. Ex : Neither he nor she can attend the meeting.",
    "gerund": "Forme en -ING utilisée comme un nom. Ex : Swimming is fun.",
    "infinitive": "TO + BV utilisé après certains verbes, adjectifs, ou pour exprimer un but. Ex : I want to go.",
    "articles (a/an/the)": "A/AN pour une chose non spécifique ; THE pour une chose spécifique ou déjà mentionnée.",
    "zero article": "Pas d'article devant des noms abstraits ou pluriels utilisés dans un sens général. Ex : Love is important.",
    "few/little": "FEW pour des choses dénombrables (peu). LITTLE pour des choses indénombrables (peu).",
    "some/any": "SOME pour des phrases affirmatives. ANY pour des phrases interrogatives ou négatives.",
    "much/many": "MANY pour des choses dénombrables (beaucoup). MUCH pour des choses indénombrables.",
    "a lot of/lots of": "Utilisé pour exprimer une grande quantité, avec des noms dénombrables et indénombrables.",
    "either/neither": "EITHER pour exprimer un choix (soit l'un, soit l'autre). NEITHER pour dire qu'aucun des deux.",
    "so/such": "SO + adj. Ex : So interesting. SUCH + nom. Ex : Such a beautiful place.",
    "make vs do": "MAKE pour créer ou produire quelque chose. DO pour des activités ou des actions générales.",
    "let vs allow": "LET + BV pour permettre. ALLOW + infinitif pour autoriser formellement.",
    "hardly/barely/scarcely": "Ces trois mots signifient presque pas et sont souvent suivis d'une négation.",
    "adjectives order": "L'ordre des adjectifs en anglais : opinion, taille, âge, forme, couleur, origine, matière, but.",
    "in spite of/despite": "Malgré : IN SPITE OF/DESPITE + nom ou gérondif (-ING).",
    "reported speech": "Changement des temps verbaux lors du passage du discours direct au discours rapporté.",
    "wish + past simple": "Utilisé pour exprimer un souhait irréaliste ou impossible dans le présent. Ex : I wish I had more time.",
    "wish + past perfect": "Utilisé pour exprimer un regret concernant une situation passée. Ex : I wish I had studied more.",
    "hope vs wish": "HOPE pour des souhaits réalistes. WISH pour des situations irréelles ou impossibles.",
    "unless": "Utilisé pour exprimer une condition négative : UNLESS = IF NOT.",
    "whereas": "WHEREAS pour exprimer un contraste entre deux idées ou situations.",
    "although/even though": "ALSOUGH/EVEN THOUGH pour exprimer une concession (bien que...).",
    "by the time": "BY THE TIME + présent simple pour parler d'une action future qui sera terminée avant une autre action.",
    "each vs every": "EACH pour des éléments individuels. EVERY pour un groupe entier. Ex : Each student gets a book. Every student has a desk.",
    "no sooner...than": "NO SOONER + inversion de sujet et auxiliaire + THAN pour exprimer une action immédiatement suivie d'une autre.",
    "either of/neither of": "EITHER OF pour choisir entre deux options. NEITHER OF pour dire qu'aucune des deux options n'est choisie.",
    "should have + past participle": "Utilisé pour exprimer un regret ou une critique par rapport à une action passée.",
    "could have + past participle": "Utilisé pour parler d'une possibilité dans le passé qui ne s'est pas réalisée.",
    "may have/might have + past participle": "Utilisé pour exprimer une possibilité dans le passé.",
    "be supposed to": "Utilisé pour parler d'une obligation ou d'une attente. Ex : You are supposed to be here at 8.",
    "such as": "Utilisé pour donner des exemples. Ex : I enjoy outdoor activities such as hiking and swimming.",
    "either way": "Utilisé pour dire que deux options sont acceptables. Ex : Either way, we will find a solution.",
    "no matter": "Utilisé pour exprimer une indifférence ou une impossibilité. Ex : No matter what happens, I will be there.",
    "wh- questions": "Utilisé pour poser des questions ouvertes avec what, where, when, why, who, how.",
    "so far": "Utilisé pour exprimer une action ou une situation qui a duré jusqu'à présent. Ex : So far, everything is going well.",
    "hard vs hardly": "HARD signifie difficile ou intensément. HARDLY signifie presque pas.",
    "both": "Utilisé pour parler de deux éléments ensemble. Ex : Both John and Mary are coming.",
    "inversion after negative adverbs": "Inversion sujet-verbe après certains adverbes négatifs pour renforcer l'emphase. Ex : Never have I seen such chaos.",
    "future perfect continuous": "WILL HAVE BEEN + V-ING pour parler d'une action continue qui sera terminée à un moment donné dans le futur. Ex : By 2025, I will have been working here for 10 years.",
    "quantifiers": "MANY, MUCH, FEW, LITTLE, SOME, ANY, A FEW, A LITTLE, etc. pour indiquer des quantités. Ex : Many people, much time.",
    "conditionals mixed tenses": "Combinaison de temps dans des phrases conditionnelles mixtes. Ex : If I had studied harder, I would have a better job now.",
    "present perfect vs past simple": "Le présent parfait est utilisé pour des actions ayant un lien avec le présent. Le passé simple est utilisé pour des actions terminées sans lien avec le présent.",
    "wish + would": "Utilisé pour exprimer des souhaits concernant des actions ou des comportements futurs que l'on souhaite changer. Ex : I wish you would stop smoking.",
    "as long as / provided that": "Utilisé pour exprimer une condition forte. Ex : You can borrow the car as long as you return it by 6.",
    "direct vs indirect questions": "Les questions directes ont l'ordre classique des questions. Les indirectes sont plus polies. Ex : What time is it? vs Can you tell me what time it is?",
    "reported questions": "Transformation des questions directes en discours indirect sans inversion sujet-verbe. Ex : He asked where I was going.",
    "had better vs should": "HAD BETTER est plus fort, impliquant des conséquences si le conseil n'est pas suivi. SHOULD est un conseil général. Ex : You'd better hurry. / You should study more.",
    "be likely to": "Utilisé pour parler d'une forte probabilité. Ex : She is likely to win the prize.",
    "prepositional verbs": "Verbes suivis de prépositions spécifiques. Ex : Look at, depend on, insist on.",
    "cleft sentences with what": "Utilisé pour insister sur un élément de la phrase. Ex : What I need is a break.",
    "past perfect continuous": "HAD BEEN + V-ING pour parler d'une action qui était en cours avant un moment passé spécifique. Ex : I had been working for 3 hours when the phone rang.",
    "present participle vs past participle": "Le présent participe (-ING) est utilisé pour des actions en cours, le passé participe (-ED ou forme irrégulière) pour des actions complétées. Ex : The running man / The broken vase.",
    "relative pronouns with prepositions": "Quand une préposition est nécessaire dans une subordonnée relative, elle peut être placée avant le pronom relatif. Ex : The company for which I work.",
    "nominalisation": "Transformer des verbes ou adjectifs en noms pour rendre un texte plus formel. Ex : Decide → Decision, Strong → Strength.",
    "neither + singular verb": "NI et un verbe au singulier. Ex : Neither of the options is good.",
    "double negatives": "L'utilisation de deux négations crée une affirmation, mais est souvent considérée comme incorrecte dans l'anglais formel. Ex : I don’t know nothing (incorrect).",
    "collocations with make and do": "Certaines expressions vont avec MAKE ou DO. Ex : Make a decision, do homework.",
    "bare infinitive": "Utilisation de l'infinitif sans TO après certains verbes comme 'let', 'make', et les modaux. Ex : Let him go. She can swim.",
    "third conditional": "IF + past perfect, WOULD HAVE + past participle pour parler d'une situation hypothétique dans le passé. Ex : If I had known, I would have helped.",
    "zero conditional": "IF + présent simple pour des vérités générales. Ex : If you heat water, it boils.",
    "modals of deduction": "Utilisation des modaux pour exprimer des déductions. Ex : He must be at home (forte certitude), He might be at home (possibilité).",
    "verb patterns with object + infinitive": "Certains verbes nécessitent un objet suivi de l'infinitif. Ex : I want you to help me.",
    "quantifiers with countable and uncountable nouns": "L'utilisation correcte de MANY avec les noms dénombrables et MUCH avec les noms indénombrables.",
    "if only": "Utilisé pour exprimer un regret fort. Ex : If only I had studied harder.",
    "so...that / such...that": "SO + adj/adv + THAT, SUCH + (adj) + nom + THAT pour indiquer la conséquence. Ex : It was so hot that we stayed inside. / It was such a hot day that we stayed inside.",
    "expressing contrast": "ALTHOUGH, EVEN THOUGH, WHILE, HOWEVER pour exprimer une opposition ou un contraste. Ex : Although it was raining, we went out.",
    "time clauses": "WHEN, AS SOON AS, UNTIL, BEFORE, AFTER sont suivis du présent pour parler d'un futur. Ex : I'll call you when I arrive.",
    "concessive clauses": "ALBEIT, EVEN THOUGH, WHILE pour exprimer une concession. Ex : He tried hard, albeit unsuccessfully.",
    "make someone do something": "MAKE + objet + base verbale pour indiquer qu'on force ou oblige quelqu'un à faire quelque chose. Ex : She made him clean his room.",
    "let someone do something": "LET + objet + base verbale pour donner la permission à quelqu'un de faire quelque chose. Ex : She let him go early.",
    "have someone do something": "HAVE + objet + base verbale pour demander à quelqu'un de faire quelque chose. Ex : I had the mechanic fix my car.",
    "get someone to do something": "GET + objet + infinitif (to + base verbale) pour persuader quelqu'un de faire quelque chose. Ex : I got him to help me with my homework.",
    "if it hadn't been for": "Utilisé pour exprimer une situation qui aurait été différente si une autre condition avait été présente. Ex : If it hadn't been for the rain, we would have gone hiking.",
    "but for": "BUT FOR + nom est utilisé pour parler de ce qui aurait pu empêcher une situation. Ex : But for her help, I wouldn't have finished on time.",
    "if not for": "IF NOT FOR est utilisé de manière similaire à 'but for'. Ex : If not for his advice, I would have failed the exam.",
    "adjectives vs adverbs": "Les adjectifs décrivent un nom et les adverbes décrivent un verbe, un adjectif, ou une autre action. Ex : She is a quick runner (adj). She runs quickly (adv).",
    "good vs well": "GOOD est un adjectif, WELL est un adverbe. Ex : She is a good singer. She sings well.",
    "late vs lately": "LATE signifie 'en retard'. LATELY signifie 'récemment'. Ex : I arrived late. / Have you seen her lately?",
    "during": "DURING + nom est utilisé pour parler d'un moment spécifique au cours d'une période. Ex : I fell asleep during the movie.",
    "as much as": "AS MUCH AS est utilisé pour comparer des quantités indénombrables ou des actions. Ex : I don’t like coffee as much as tea.",
    "the same as": "THE SAME AS est utilisé pour indiquer que deux choses sont identiques. Ex : This dress is the same as mine.",
    "more than": "MORE THAN est utilisé pour comparer deux éléments et montrer une différence en quantité ou en intensité. Ex : She earns more than her brother.",
    "less than": "LESS THAN est utilisé pour montrer une infériorité ou une moindre quantité. Ex : He has less time than I do.",
    "because vs because of": "BECAUSE + sujet + verbe, BECAUSE OF + nom. Ex : We stayed home because it was raining. / We stayed home because of the rain.",
    "therefore / consequently": "Utilisé pour indiquer une conséquence directe. Ex : It was raining; therefore, we stayed home.",
    "so / so that": "SO pour une conséquence, SO THAT pour exprimer un but. Ex : It was late, so we left. / I studied hard so that I could pass the test.",
    "prepositions of time": "IN + mois/année (ex : in July, in 2024), ON + jour/date (ex : on Monday, on July 5th), AT + heure précise (ex : at 6 PM).",
    "prepositions of place": "IN pour un espace clos, ON pour une surface, AT pour un point précis. Ex : She is in the room, the book is on the table, meet me at the station.",
    "prepositions after adjectives": "Certains adjectifs sont suivis de prépositions spécifiques. Ex : interested in, good at, famous for.",
    "can vs could": "CAN pour la capacité ou la permission dans le présent. COULD est plus poli ou utilisé pour des possibilités passées. Ex : Can I leave early? / Could you help me, please?",
    "should vs ought to": "SHOULD et OUGHT TO pour donner un conseil. Ex : You should exercise more. / You ought to see a doctor.",
    "verbs + infinitive": "Certains verbes sont suivis de l'infinitif. Ex : I want to go, He needs to finish.",
    "verbs + gerund": "Certains verbes sont suivis du gérondif (-ING). Ex : I enjoy reading, She avoids talking to strangers.",
    "verbs + object + infinitive": "Certains verbes nécessitent un objet avant l'infinitif. Ex : I asked him to help me.",
    "gerund after prepositions": "Le gérondif est utilisé après des prépositions. Ex : She is good at playing tennis.",
    "phrasal verbs with up": "Exemples : Give up (abandonner), Set up (installer), Pick up (ramasser).",
    "phrasal verbs with out": "Exemples : Find out (découvrir), Run out of (manquer de), Turn out (se révéler être).",
    "phrasal verbs with on": "Exemples : Go on (continuer), Rely on (compter sur), Call on (faire appel à).",
    "who vs which vs that": "WHO est utilisé pour les personnes, WHICH pour les choses, THAT peut être utilisé pour les deux (dans les propositions restrictives). Ex : The man who called is my brother. / The book which I read was great. / The car that I bought is new.",
    "whose": "Utilisé pour indiquer la possession. Ex : The woman whose car was stolen is at the police station.",
    "relative clauses without pronouns": "Dans certaines propositions relatives, le pronom peut être omis s'il est l'objet. Ex : The book (that) I read was amazing."
}
