quiz_questions = [
    ("If I _______ you, I wouldn’t take that risk.", ["was", "were", "am"], "B"),
    ("I regret _______ him that secret.", ["tell", "to tell", "telling"], "C"),
    ("She had her house _______ last year.", ["painted", "painting", "to paint"], "A"),
    ("By the time we arrived, the show _______.", ["had already started", "has already started", "already started"], "A"),
    ("I wish I _______ more time to travel.", ["had", "have", "will have"], "A"),
    ("If only he _______ harder, he would have passed.", ["studies", "had studied", "would study"], "B"),
    ("She suggested _______ to the new restaurant downtown.", ["to go", "going", "go"], "B"),
    ("Not only _______ the book, but he also made a documentary.", ["he wrote", "did he write", "wrote he"], "B"),
    ("He denied _______ the money.", ["to steal", "stealing", "steal"], "B"),
    ("They were used to _______ in cold weather.", ["live", "living", "to live"], "B"),
    ("We would rather you _______ later.", ["come", "came", "will come"], "B"),
    ("If she _______ earlier, she wouldn’t have missed the train.", ["left", "had left", "leaves"], "B"),
    ("No sooner _______ the meeting started than he walked out.", ["had", "did", "has"], "A"),
    ("I can't stand _______ in traffic.", ["to wait", "waiting", "wait"], "B"),
    ("He insisted on _______ the bill.", ["pay", "paying", "to pay"], "B"),
    ("He is said _______ a fortune in real estate.", ["to make", "to have made", "making"], "B"),
    ("If I hadn’t been so tired, I _______ the party.", ["would have enjoyed", "enjoyed", "would enjoy"], "A"),
    ("She didn’t let me _______ my opinion.", ["express", "expressing", "to express"], "A"),
    ("It’s high time we _______ a decision.", ["make", "made", "have made"], "B"),
    ("Hardly _______ home when it started to rain.", ["had I arrived", "I had arrived", "have I arrived"], "A"),
    ("He has difficulty _______ in large groups.", ["speaking", "speak", "to speak"], "A"),
    ("He objected to _______ treated unfairly.", ["be", "being", "to be"], "B"),
    ("I needn’t _______ so much food.", ["to buy", "have bought", "buying"], "B"),
    ("I’d rather you _______ about this.", ["not talk", "don’t talk", "not talked"], "C"),
    ("The film was so boring that I _______ asleep.", ["fell", "have fallen", "was falling"], "A"),
    ("You must be tired after _______ all day.", ["work", "working", "to work"], "B"),
    ("I can’t help _______ when I watch that movie.", ["cry", "crying", "to cry"], "B"),
    ("She was accused of _______ confidential information.", ["leaking", "leak", "to leak"], "A"),
    ("You should have _______ me earlier.", ["call", "called", "calling"], "B"),
    ("The book is worth _______.", ["to read", "reading", "read"], "B"),
    ("I'd rather you _______ home now.", ["went", "go", "will go"], "A"),
    ("He was too tired _______ any further.", ["to walk", "walk", "walking"], "A"),
    ("He seems _______ a good time at the party.", ["having", "have had", "to have had"], "C"),
    ("She is believed _______ the crime.", ["to commit", "to have committed", "committing"], "B"),
    ("The manager demanded that he _______ on time.", ["be", "is", "was"], "A"),
    ("We are looking forward to _______ you.", ["seeing", "see", "to see"], "A"),
    ("If I had known, I _______ earlier.", ["will come", "would come", "would have come"], "C"),
    ("You had better _______ now.", ["leaving", "leave", "to leave"], "B"),
    ("The teacher made us _______ the test again.", ["do", "to do", "doing"], "A"),
    ("He had difficulty _______ the heavy box.", ["to carry", "carrying", "carry"], "B"),
    ("She denied _______ anything wrong.", ["to do", "doing", "do"], "B"),
    ("I can’t afford _______ a new car.", ["buying", "to buy", "buy"], "B"),
    ("It's no use _______ to him.", ["talking", "talk", "to talk"], "A"),
    ("You should avoid _______ too much sugar.", ["eat", "eating", "to eat"], "B"),
    ("He is used to _______ early.", ["waking up", "wake up", "wakes up"], "A"),
    ("They had difficulty _______ the car.", ["repairing", "to repair", "repair"], "A"),
    ("He went on _______ about his problems.", ["talking", "talk", "to talk"], "A"),
    ("She is busy _______ emails.", ["writing", "write", "to write"], "A"),
    ("I prefer _______ tea to coffee.", ["drink", "drinking", "to drink"], "B"),
    ("She kept _______ during the lecture.", ["yawning", "yawn", "to yawn"], "A"),
    ("Choose the correct structure: Had I known about the meeting, I ______ earlier.", 
     ["would have come", "had come", "came"], "A"),
    ("Which sentence is correct?", 
     ["Scarcely had we arrived when it started to rain.", "Scarcely we had arrived when it started to rain.", "Scarcely had we arrived than it started to rain."], "A"),
    ("Identify the correct sentence:", 
     ["She accused him of stealing the documents.", "She accused him for stealing the documents.", "She accused him to steal the documents."], "A"),
    ("Choose the correct preposition: He takes great pride ______ his work.", 
     ["in", "on", "at"], "A"),
    ("Choose the correct sentence:", 
     ["She doesn’t mind people to talk loudly.", "She doesn’t mind people talking loudly.", "She doesn’t mind that people talk loudly."], "B"),
    ("Choose the correct word: His speech was ______ than I expected.", 
     ["far more convincing", "much convincing", "many convincing"], "A"),
    ("Choose the correct word: You can’t deny ______ a mistake.", 
     ["having made", "to have made", "to make"], "A"),
    ("Choose the correct structure: So little ______ about the topic that he couldn't contribute.", 
     ["he knew", "did he know", "he did know"], "B"),
    ("Choose the correct preposition: This policy applies ______ all employees.", 
     ["to", "for", "on"], "A"),
    ("Which of these sentences is correct?", 
     ["The more you study, the better you perform.", "More you study, better you perform.", "The more you study, better you perform."], "A"),
    ("Choose the correct structure: I regret ______ him that secret.", 
     ["to tell", "telling", "tell"], "B"),
    ("Choose the correct sentence:", 
     ["She denied to have spoken to him.", "She denied having spoken to him.", "She denied that she spoke to him."], "B"),
    ("Choose the correct word: This approach is ______ effective than we had anticipated.", 
     ["far more", "much more", "a lot"], "A"),
    ("Choose the correct preposition: The manager was blamed ______ the failure of the project.", 
     ["for", "on", "to"], "A"),
    ("Choose the correct structure: Little ______ about the real reason behind his departure.", 
     ["is known", "it is known", "knows"], "A"),
    ("Choose the correct sentence:", 
     ["Not only did she finish early, but she also helped others.", "Not only she finished early, but she also helped others.", "Not only did she finish early, but also helped others."], "A"),
    ("Choose the correct preposition: He is indifferent ______ what others think of him.", 
     ["to", "for", "with"], "A"),
    ("Choose the correct structure: I object ______ treated unfairly.", 
     ["to being", "to be", "being"], "A"),
    ("Choose the correct word: His argument was so well-structured that it was impossible to ______.", 
     ["refute", "deny", "argue"], "A"),
    ("Which is the correct sentence?", 
     ["You must avoid making unnecessary mistakes.", "You must avoid to make unnecessary mistakes.", "You must avoid make unnecessary mistakes."], "A"),
    ("Choose the correct structure: Not only ______ the book, but he also made a documentary.", 
     ["he wrote", "did he write", "wrote he"], "B"),
    ("Which is the correct sentence?", 
     ["It is no use to argue with him.", "It is no use arguing with him.", "It is no use argue with him."], "B"),
    ("Choose the correct preposition: His behavior is inconsistent ______ his values.", 
     ["with", "to", "for"], "A"),
    ("Choose the correct sentence:", 
     ["She is used to waking up early.", "She is used to wake up early.", "She is used waking up early."], "A"),
    ("Choose the correct word: The manager demanded that he ______ on time.", 
     ["be", "is", "was"], "A"),
    ("Choose the correct preposition: We are looking forward ______ your response.", 
     ["to", "for", "at"], "A"),
    ("Choose the correct structure: I wish she ______ more effort into her work.", 
     ["would put", "puts", "put"], "A"),
    ("Choose the correct word: It's high time he ______ his priorities straight.", 
     ["got", "get", "gets"], "A"),
    ("Which is the correct sentence?", 
     ["I wish I were taller.", "I wish I was taller.", "I wish I am taller."], "A"),
    ("Choose the correct preposition: This task is not relevant ______ our discussion.", 
     ["to", "for", "on"], "A"),
    ("Choose the correct word: The professor insisted that the report ______ before Friday.", 
     ["be submitted", "is submitted", "was submitted"], "A"),
    ("Which sentence is correct?", 
     ["She had hardly sat down when the phone rang.", "She had hardly sat down than the phone rang.", "She had hardly sat down as the phone rang."], "A"),
    ("Choose the correct preposition: She is keen ______ learning new languages.", 
     ["on", "in", "at"], "A"),
    ("Choose the correct structure: I was made ______ my mistakes.", 
     ["to realize", "realize", "realizing"], "A"),
    ("Choose the correct word: The company is committed ______ reducing waste.", 
     ["to", "for", "with"], "A")
]

